import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
    title: "Posts by Users",
    description: "Get all posts generated by users",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div
            className={`
                flex w-full ml-[25%]
            `}
        >
            {children}
        </div>
    );
}
