import type { Metadata } from "next";
import "@/app/globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div
            className={`
                flex h-screen w-full ml-[25%]
            `}
        >
            {children}
        </div>
    );
}
